# Generated by Django 5.2.10 on 2026-02-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiggy_db',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('ratings', models.FloatField()),
                ('cuisine', models.EmailField(max_length=254)),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('Mobile_no', models.IntegerField()),
            ],
        ),
    ]
